plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'fr.cldac'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://repo.codemc.io/repository/maven-releases/' }
    maven { url 'https://repo.codemc.io/repository/maven-snapshots/' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT'
    implementation 'com.github.retrooper:packetevents-spigot:2.7.0'
}

shadowJar {
    archiveClassifier.set('')
    archiveBaseName.set('CLDAC')
    relocate 'com.github.retrooper.packetevents', 'fr.cldac.libs.packetevents'
    relocate 'io.github.retrooper.packetevents', 'fr.cldac.libs.packetevents.impl'
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
